const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const sourceDirs = ['components', 'constants', 'context', 'screens'];
const extensions = new Set(['.ts', '.tsx', '.js', '.jsx']);
const colorPattern = /#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)/g;

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(fullPath);
    return extensions.has(path.extname(entry.name)) ? [fullPath] : [];
  });
}

const inventory = new Map();
for (const sourceDir of sourceDirs) {
  const absoluteDir = path.join(root, sourceDir);
  if (!fs.existsSync(absoluteDir)) continue;
  for (const file of walk(absoluteDir)) {
    const relative = path.relative(root, file).replaceAll('\\', '/');
    const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
    lines.forEach((line, index) => {
      for (const match of line.matchAll(colorPattern)) {
        const color = match[0].toUpperCase();
        const entries = inventory.get(color) ?? [];
        entries.push(`${relative}:${index + 1}`);
        inventory.set(color, entries);
      }
    });
  }
}

const approved = new Map([
  ['#315FAE', 'Primary blue'],
  ['#214986', 'Dark blue'],
  ['#EAF1FC', 'Soft blue'],
  ['#F6F7F9', 'Canvas'],
  ['#FFFFFF', 'Surface / white'],
  ['#F1F3F6', 'Alternative surface'],
  ['#172238', 'Primary text'],
  ['#526078', 'Muted text'],
  ['#7A879A', 'Soft text'],
  ['#DDE2EA', 'Border'],
  ['#247A55', 'Success'],
  ['#E8F3ED', 'Success surface'],
  ['#B54747', 'Error'],
  ['#F8EAEA', 'Error surface'],
  ['#000000', 'Black media surface'],
  ['#FFCC00', 'Approved MTN provider mark'],
  ['#E3242B', 'Approved Airtel provider mark'],
]);

function recommendation(color) {
  if (approved.has(color)) return approved.get(color);
  if (color.startsWith('RGBA(')) return 'Replace with a semantic token or retain only for modal/media overlays';
  return 'Replace with the nearest semantic theme token';
}

const rows = [...inventory.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([color, locations]) => {
    const shown = locations.slice(0, 8).map((location) => `\`${location}\``).join('<br>');
    const remainder = locations.length > 8 ? `<br>+${locations.length - 8} more` : '';
    return `| \`${color}\` | ${locations.length} | ${recommendation(color)} | ${shown}${remainder} |`;
  });

const occurrenceCount = [...inventory.values()].reduce((sum, entries) => sum + entries.length, 0);
const report = `# Color Audit

Generated by \`npm run audit:colors\`.

## Baseline

The pre-refinement scan contained **141 unique color values across 305 occurrences**. The table below is the current regeneratable inventory after the professional UI/UX refinement.

## Approved Palette

- Primary blue: \`#315FAE\`
- Dark blue: \`#214986\`
- Soft blue: \`#EAF1FC\`
- Neutral canvas, surfaces, text, and borders from \`constants/theme.ts\`
- Green and red only for meaningful success and error states
- \`#FFCC00\` and \`#E3242B\` only for MTN and Airtel provider identifiers

## Current Inventory

**${inventory.size} unique values across ${occurrenceCount} occurrences**

| Color | Count | Intended replacement or exception | Locations |
| --- | ---: | --- | --- |
${rows.join('\n')}

## Follow-up Rule

New product UI colors should be added to \`constants/theme.ts\` first. Hardcoded colors are acceptable only for provider marks, media surfaces, or technically required document rendering.
`;

const docsDir = path.join(root, 'docs');
fs.mkdirSync(docsDir, { recursive: true });
fs.writeFileSync(path.join(docsDir, 'color-audit.md'), report);
console.log(`Wrote docs/color-audit.md (${inventory.size} colors, ${occurrenceCount} occurrences).`);
