const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const sourceDirs = ['components', 'constants', 'context', 'screens'];
const extensions = new Set(['.ts', '.tsx', '.js', '.jsx']);
const colorPattern = /#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)/g;

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(fullPath);
    return extensions.has(path.extname(entry.name)) ? [fullPath] : [];
  });
}

const inventory = new Map();
for (const sourceDir of sourceDirs) {
  const absoluteDir = path.join(root, sourceDir);
  if (!fs.existsSync(absoluteDir)) continue;
  for (const file of walk(absoluteDir)) {
    const relative = path.relative(root, file).replaceAll('\\', '/');
    const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
    lines.forEach((line, index) => {
      for (const match of line.matchAll(colorPattern)) {
        const color = match[0].toUpperCase();
        const entries = inventory.get(color) ?? [];
        entries.push(`${relative}:${index + 1}`);
        inventory.set(color, entries);
      }
    });
  }
}

const approved = new Map([
  ['#2563EB', 'Primary blue'],
  ['#2D5FBF', 'Secondary / deep blue'],
  ['#1E3A8A', 'Dark emphasis'],
  ['#F9FAFB', 'Background'],
  ['#FFFFFF', 'Surface / white'],
  ['#F3F4F6', 'Surface alt'],
  ['#EFF6FF', 'Light blue tint / info soft'],
  ['#111827', 'Text primary'],
  ['#374151', 'Text secondary'],
  ['#6B7280', 'Text muted'],
  ['#E5E7EB', 'Border'],
  ['#10B981', 'Success'],
  ['#DCFCE7', 'Success surface'],
  ['#F59E0B', 'Warning'],
  ['#FFFBEB', 'Warning surface'],
  ['#F05252', 'Error'],
  ['#FDE8E8', 'Error surface'],
  ['#1C64F2', 'Info / link tint'],
  ['#000000', 'Black media surface'],
  ['#000', 'Black media surface shorthand'],
  ['#FFCC00', 'Approved MTN provider mark'],
  ['#E3242B', 'Approved Airtel provider mark'],
  ['RGBA(0,0,0,0.05)', 'Subtle technical border/shadow transparency'],
  ['RGBA(107, 114, 128, 0.22)', 'PDF watermark transparency'],
  ['RGBA(15, 23, 42, 0.08)', 'PDF rendering shadow transparency'],
  ['RGBA(15, 23, 42, 0.45)', 'Modal/media overlay transparency'],
  ['RGBA(15, 23, 42, 0.62)', 'Modal overlay transparency'],
  ['RGBA(15, 23, 42, 0.65)', 'Modal overlay transparency'],
  ['RGBA(17,24,39,0.12)', 'Theme overlay soft token'],
  ['RGBA(17,24,39,0.48)', 'Theme overlay token'],
  ['RGBA(20,33,58,0.22)', 'Modal overlay transparency'],
  ['RGBA(20,33,58,0.42)', 'Media overlay transparency'],
  ['RGBA(20,33,58,0.62)', 'Gate modal overlay transparency'],
  ['RGBA(221,226,234,0.92)', 'Exam modal border transparency'],
  ['RGBA(229,231,235,0.78)', 'Floating nav border transparency'],
  ['RGBA(23, 34, 56, 0.46)', 'Road-sign modal overlay transparency'],
  ['RGBA(249,250,251,0.86)', 'Floating nav frosted shelf transparency'],
  ['RGBA(255,255,255,0.12)', 'Header/card surface transparency'],
  ['RGBA(255,255,255,0.13)', 'Header/card surface transparency'],
  ['RGBA(255,255,255,0.14)', 'Header/card surface transparency'],
  ['RGBA(255,255,255,0.16)', 'Header/card surface transparency'],
  ['RGBA(255,255,255,0.22)', 'Header/card surface transparency'],
  ['RGBA(255,255,255,0.25)', 'Media card border transparency'],
  ['RGBA(255,255,255,0.78)', 'Header eyebrow text transparency'],
  ['RGBA(255,255,255,0.98)', 'Floating nav surface transparency'],
  ['RGBA(74, 120, 208, 0.18)', 'PDF spinner transparency'],
]);

function recommendation(color) {
  if (approved.has(color)) return approved.get(color);
  if (color.startsWith('RGBA(')) return 'Replace with a semantic token or retain only for modal/media overlays';
  return 'Replace with the nearest semantic theme token';
}

const rows = [...inventory.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([color, locations]) => {
    const shown = locations.slice(0, 8).map((location) => `\`${location}\``).join('<br>');
    const remainder = locations.length > 8 ? `<br>+${locations.length - 8} more` : '';
    return `| \`${color}\` | ${locations.length} | ${recommendation(color)} | ${shown}${remainder} |`;
  });

const occurrenceCount = [...inventory.values()].reduce((sum, entries) => sum + entries.length, 0);
const report = `# Color Audit

Generated by \`npm run audit:colors\`.

## Baseline

The pre-refinement scan contained **141 unique color values across 305 occurrences**. The table below is the current regeneratable inventory after the professional UI/UX refinement.

## Approved Palette

- Primary blue: \`#2563EB\`
- Secondary / deep blue: \`#2D5FBF\`
- Dark emphasis: \`#1E3A8A\`
- Light blue tint: \`#EFF6FF\`
- Neutral canvas, surfaces, text, and borders from \`constants/theme.ts\`
- Green, amber, and red only for meaningful success, warning, and error states
- \`#FFCC00\` and \`#E3242B\` only for MTN and Airtel provider identifiers

## Current Inventory

**${inventory.size} unique values across ${occurrenceCount} occurrences**

| Color | Count | Intended replacement or exception | Locations |
| --- | ---: | --- | --- |
${rows.join('\n')}

## Follow-up Rule

New product UI colors should be added to \`constants/theme.ts\` first. Hardcoded colors are acceptable only for provider marks, media surfaces, or technically required document rendering.
`;

const docsDir = path.join(root, 'docs');
fs.mkdirSync(docsDir, { recursive: true });
fs.writeFileSync(path.join(docsDir, 'color-audit.md'), report);
console.log(`Wrote docs/color-audit.md (${inventory.size} colors, ${occurrenceCount} occurrences).`);
